jobs:
  include:
    - stage: test
      script:
        - docker build --target all_tests -t test .
        - docker run --name todo-app-test --env TRELLO_URL --env TRELLO_KEY --env TRELLO_BOARD_ID --env TRELLO_TOKEN test
    - stage: deploy
      script:
        - DOCKER_TAG="$DOCKER_USERNAME/todo-app:$TRAVIS_COMMIT"
        - docker build --target prod -t $DOCKER_TAG .
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - docker push $DOCKER_TAG
